<template>
  <div class="vld-parent">
    <loading :active="isLoading">
      <div class="loadingio-spinner-ripple-wu44vrvts1">
        <div class="ldio-2gn8nvj94zp">
          <div></div>
          <div></div>
        </div>
      </div>
    </loading>
    <div class="storyAll" v-for="(item, index) in story" :key="index">
      <div class="story">
        <div class="storyOutline" @click.prevent="doAjax">
          <img :src="item.img" alt="" />
        </div>
        <h3>{{ item.title }}</h3>
      </div>
    </div>
  </div>
  <div v-if="isShow" class="storyShow">
    <img src="public/images/cat.jpeg" alt="" />
    <div class="storySend">
      <input type="text" placeholder="發送訊息" />
      <button class="storyButton">
        <span class="material-symbols-outlined" @click="showOver">favorite</span>
        <span class="material-symbols-outlined" @click="showOver">arrow_circle_right</span>
      </button>
    </div>
  </div>
</template>

<script>
import Loading from 'vue3-loading-overlay/dist/index'
import 'vue3-loading-overlay/dist/vue3-loading-overlay.css'
export default {
  data() {
    return {
      isLoading: false,
      fullPage: true,
      story: [
        {
          img: 'public/images/landscape.jpeg',
          title: 'LandScape'
        },
        { img: 'public/images/camping.jpeg', title: 'Camping' },
        { img: 'public/images/food.jpeg', title: 'Food' },
        { img: 'public/images/drinks.png', title: 'Cafe' },
        { img: 'public/images/books.jpg', title: 'Book' },
        { img: 'public/images/makeup.jpg', title: 'makeup' },
        { img: 'public/images/airplane.jpg', title: 'GoAboard' },
        { img: 'public/images/music.jpg', title: 'Music' }
      ],
      isShow: false
    }
  },
  components: {
    Loading
  },
  methods: {
    doAjax() {
      this.isLoading = true
      // simulate AJAX
      setTimeout(() => {
        this.isLoading = false
        this.isShow = true
      }, 1000)
    },
    showOver() {
      this.isShow = false
    }
  }
}
</script>

<style scoped>
.vld-parent {
  display: flex;
  text-align: center;
  gap: 30px;
  position: relative;
  overflow-x: scroll;
  margin-top: 50px;
}
.story {
  display: block;
}
.storyOutline {
  border: solid 1px #efefef;
  width: 120px;
  height: 120px;
  border-radius: 100%;
  overflow: hidden;
  cursor: pointer;
}
.storyOutline img {
  width: 100%;
  height: 100%;
}
h3 {
  margin-top: 10px;
}
.storyShow {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 100;
  border: solid 1px black;
  border-radius: 5% 5% 3% 3%;
  background-color: black;
}

.storyShow img {
  display: block;
  border-radius: 5% 5% 0% 0%;
}
.storySend {
  /* position: absolute;
  bottom: 0%;
  left: 50%;
  transform: translate(-50%, -50%); */
  display: flex;
  align-items: center;
  justify-content: space-evenly;
  padding: 10px;
}
.storySend input {
  border-radius: 999em;
  border: solid 1px white;
  width: 240px;
  height: 32px;
  padding: 20px;
  background-color: transparent;
  color: white;
}
.storySend input::placeholder {
  color: white;
}
.storyButton {
  border: none;
  background-color: transparent;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 14px;
  color: white;
}
.storyButton span {
  font-size: 32px;
  border-radius: 999em;
  cursor: pointer;
}

@keyframes ldio-2gn8nvj94zp {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}

.ldio-2gn8nvj94zp div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-2gn8nvj94zp 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}

.ldio-2gn8nvj94zp div:nth-child(1) {
  border-color: #1d3f72;
}

.ldio-2gn8nvj94zp div:nth-child(2) {
  border-color: #5699d2;
  animation-delay: -0.5s;
}

.loadingio-spinner-ripple-wu44vrvts1 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  /*  background 設定 none  */
  background: none;
}
.ldio-2gn8nvj94zp {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2gn8nvj94zp div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
